
// This file has been generated by the GUI designer. Do not modify.
namespace learning
{
	public partial class TotallyTestingWidget
	{
		private global::Gtk.Fixed fixed3;
		private global::Gtk.Button button6;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget learning.TotallyTestingWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "learning.TotallyTestingWidget";
			// Container child learning.TotallyTestingWidget.Gtk.Container+ContainerChild
			this.fixed3 = new global::Gtk.Fixed ();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.button6 = new global::Gtk.Button ();
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseUnderline = true;
			this.button6.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.fixed3.Add (this.button6);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.button6]));
			w1.X = 151;
			w1.Y = 49;
			this.Add (this.fixed3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
